package ai.chat2db.community.web.api.config.web.auth;

import java.security.SecureRandom;
import java.time.Duration;
import java.time.Instant;
import java.util.Base64;
import java.util.Iterator;
import java.util.Map;
import java.util.Optional;
import java.util.concurrent.ConcurrentHashMap;

import jakarta.annotation.PostConstruct;
import lombok.extern.slf4j.Slf4j;
import org.apache.commons.lang3.StringUtils;
import org.springframework.stereotype.Component;

/**
 * Sign-in for the Community web deployment.
 *
 * Chat2DB Community has no accounts of its own, and every saved datasource
 * password and AI key is readable by whoever can reach the port. That is fine on
 * a desktop and not fine on a server, so this puts named accounts in front of
 * the whole API.
 *
 * An account owns a workspace: its datasources, consoles and history live in a
 * directory of their own and are not visible to anyone else, an admin included.
 * The role decides who may manage accounts, not who may see what.
 *
 * What that does not buy: a connection carries database credentials, and whoever
 * holds it can do whatever those credentials allow. Keeping someone out of a
 * table is still the database's job.
 *
 * The first start creates an {@code admin} account from
 * CHAT2DB_COMMUNITY_PASSWORD - which the container entrypoint generates and
 * prints when the operator has not set one - so there is always a way in and
 * never a step to get wrong.
 */
@Slf4j
@Component
public class CommunityAccessGuard {

    /** Session cookie name. Prefixed like the storage keys so it is recognisable. */
    public static final String SESSION_COOKIE = "chat2db_community_session";

    /** The account the first start creates. */
    public static final String BOOTSTRAP_USERNAME = "admin";

    /** Set by the operator. Authoritative: it is the admin password, every start. */
    private static final String PASSWORD_PROPERTY = "chat2db.community.password";
    private static final String PASSWORD_ENV = "CHAT2DB_COMMUNITY_PASSWORD";

    /**
     * Generated by the container when the operator set nothing. Seeds the first
     * admin and is then left alone, so a password changed in the interface is
     * not overwritten on the next restart.
     */
    private static final String BOOTSTRAP_PASSWORD_PROPERTY = "chat2db.community.bootstrap-password";
    private static final String BOOTSTRAP_PASSWORD_ENV = "CHAT2DB_COMMUNITY_BOOTSTRAP_PASSWORD";
    private static final String DISABLE_PROPERTY = "chat2db.community.disable-login";
    private static final String DISABLE_ENV = "CHAT2DB_DISABLE_LOGIN";

    /** Long enough not to be a daily annoyance, short enough to expire eventually. */
    public static final Duration SESSION_TTL = Duration.ofDays(7);

    /**
     * Sessions live in memory only. A restart signs everybody out, which is the
     * right trade for a single-container deployment: no shared secret to persist
     * and no stale token that outlives a password change.
     */
    private final Map<String, Session> sessions = new ConcurrentHashMap<>();
    private final SecureRandom random = new SecureRandom();
    private final CommunityUserStore users;

    public CommunityAccessGuard(CommunityUserStore users) {
        this.users = users;
    }

    private record Session(String username, Instant expiresAt) {
    }

    @PostConstruct
    void bootstrap() {
        if (isDisabled()) {
            log.warn("[chat2db] Sign-in is disabled: anyone who can reach this port has full access to every "
                    + "stored connection. Unset CHAT2DB_DISABLE_LOGIN to require accounts.");
            return;
        }
        applyOperatorPassword();

        if (users.isEmpty()) {
            String password = bootstrapPassword();
            if (StringUtils.isBlank(password)) {
                log.error("[chat2db] No accounts exist and no password is configured, so no admin account could "
                        + "be created. Set CHAT2DB_COMMUNITY_PASSWORD and restart, or nobody can sign in.");
                return;
            }
            users.create(BOOTSTRAP_USERNAME, password, CommunityRole.ADMIN);
            // Says where the password can be read rather than which variable
            // carried it: the container puts a generated one into a variable
            // too, so naming a variable sends people looking in a .env file
            // that never had it.
            log.info("[chat2db] Created the '{}' account. Its password was printed above, and is readable with: "
                    + "docker exec <container> cat /root/.chat2db-community/config/password. Sign in, then add "
                    + "accounts for everyone else in Settings > Account.", BOOTSTRAP_USERNAME);
        }
        log.info("[chat2db] Sign-in is ENABLED with {} account(s). Sessions expire after {} days.",
                users.list().size(), SESSION_TTL.toDays());
    }

    /** Whether the gate is up at all. */
    public boolean isEnabled() {
        return !isDisabled();
    }

    /**
     * Checks a username and password.
     *
     * A disabled account and a wrong password are answered identically, so the
     * screen cannot be used to learn which accounts exist.
     */
    public Optional<CommunityUser> authenticate(String username, String password) {
        Optional<CommunityUser> candidate = users.find(username);
        // Verify even when the account is missing or disabled, so the reply takes
        // the same time either way and does not leak which usernames are real.
        String storedHash = candidate.map(CommunityUser::getPasswordHash).orElse("");
        boolean passwordMatches = PasswordHasher.verify(password, storedHash);
        if (!passwordMatches || candidate.isEmpty() || !candidate.get().isEnabled()) {
            return Optional.empty();
        }
        return candidate;
    }

    /** Creates a session for an authenticated account and returns its token. */
    public String issueSession(String username) {
        pruneExpired();
        byte[] token = new byte[32];
        random.nextBytes(token);
        String value = Base64.getUrlEncoder().withoutPadding().encodeToString(token);
        sessions.put(value, new Session(username, Instant.now().plus(SESSION_TTL)));
        return value;
    }

    /**
     * The account behind a session token, if it is still valid.
     *
     * Re-read from the store on every request rather than trusted from the
     * session, so disabling an account or changing its role takes effect at once
     * instead of whenever that person next signs in.
     */
    public Optional<CommunityUser> resolveSession(String token) {
        if (StringUtils.isBlank(token)) {
            return Optional.empty();
        }
        Session session = sessions.get(token);
        if (session == null) {
            return Optional.empty();
        }
        if (session.expiresAt().isBefore(Instant.now())) {
            sessions.remove(token);
            return Optional.empty();
        }
        Optional<CommunityUser> user = users.find(session.username());
        if (user.isEmpty() || !user.get().isEnabled()) {
            sessions.remove(token);
            return Optional.empty();
        }
        return user;
    }

    public boolean isValidSession(String token) {
        return resolveSession(token).isPresent();
    }

    public void revokeSession(String token) {
        if (StringUtils.isNotBlank(token)) {
            sessions.remove(token);
        }
    }

    /** Ends every session belonging to an account, used when it is disabled or deleted. */
    public void revokeSessionsFor(String username) {
        if (StringUtils.isBlank(username)) {
            return;
        }
        sessions.entrySet().removeIf(entry -> entry.getValue().username().equalsIgnoreCase(username.trim()));
    }

    void pruneExpired() {
        Instant now = Instant.now();
        Iterator<Map.Entry<String, Session>> entries = sessions.entrySet().iterator();
        while (entries.hasNext()) {
            if (entries.next().getValue().expiresAt().isBefore(now)) {
                entries.remove();
            }
        }
    }

    int sessionCount() {
        return sessions.size();
    }

    private boolean isDisabled() {
        String configured = System.getProperty(DISABLE_PROPERTY);
        if (StringUtils.isBlank(configured)) {
            configured = System.getenv(DISABLE_ENV);
        }
        return "true".equalsIgnoreCase(StringUtils.trimToEmpty(configured));
    }

    /**
     * Makes CHAT2DB_COMMUNITY_PASSWORD mean what an operator reads it to mean:
     * this is the admin password, now, whatever the account file says.
     *
     * It used to seed the first admin and then be ignored forever, so setting it
     * on an existing installation looked like it had done nothing - no error, no
     * log line, just a sign-in that kept failing. It is also the only way back in
     * when the admin password is lost, which is precisely when it must work.
     *
     * The account is restored whole - existing, enabled, admin - because half of
     * a recovery lever is no lever. Sessions on that account end with the reset.
     *
     * Applied only when the password actually differs, so a restart neither
     * rewrites the file nor signs anybody out for nothing.
     */
    private void applyOperatorPassword() {
        String password = operatorPassword();
        if (StringUtils.isBlank(password)) {
            return;
        }
        Optional<CommunityUser> existing = users.find(BOOTSTRAP_USERNAME);
        if (existing.isEmpty()) {
            return;  // Nothing to correct; the bootstrap below creates it.
        }
        CommunityUser admin = existing.get();
        boolean passwordMatches = PasswordHasher.verify(password, admin.getPasswordHash());
        if (passwordMatches && admin.isEnabled() && admin.isAdmin()) {
            return;
        }
        if (!passwordMatches) {
            users.setPassword(BOOTSTRAP_USERNAME, password);
            revokeSessionsFor(BOOTSTRAP_USERNAME);
        }
        if (!admin.isEnabled()) {
            users.setEnabled(BOOTSTRAP_USERNAME, true);
        }
        if (!admin.isAdmin()) {
            users.setRole(BOOTSTRAP_USERNAME, CommunityRole.ADMIN);
        }
        log.warn("[chat2db] Reset the '{}' account from CHAT2DB_COMMUNITY_PASSWORD. Unset that variable once you "
                + "are back in, or every restart will reset it again.", BOOTSTRAP_USERNAME);
    }

    /** What the operator set, if anything. */
    private String operatorPassword() {
        String configured = System.getProperty(PASSWORD_PROPERTY);
        if (StringUtils.isBlank(configured)) {
            configured = System.getenv(PASSWORD_ENV);
        }
        return configured;
    }

    /** What the first admin is created from: the operator's, else the container's. */
    private String bootstrapPassword() {
        String configured = operatorPassword();
        if (StringUtils.isNotBlank(configured)) {
            return configured;
        }
        configured = System.getProperty(BOOTSTRAP_PASSWORD_PROPERTY);
        if (StringUtils.isBlank(configured)) {
            configured = System.getenv(BOOTSTRAP_PASSWORD_ENV);
        }
        return configured;
    }
}
